version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    # To be aligned with opendatahub-operator codebase these dependencies are ignored for now
    ignore:
      - dependency-name: "sigs.k8s.io/*"
      - dependency-name: "k8s.io/*"
    reviewers:
      - aslakknutsen
      - bartoszmajsak
      - cam-garrison

  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    reviewers:
      - aslakknutsen
      - bartoszmajsak
      - cam-garrison

  - package-ecosystem: "github-actions"
    directory: "/" # resolved as .github/workflows
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    reviewers:
      - aslakknutsen
      - bartoszmajsak
      - cam-garrison
