linters-settings:
  depguard:
    rules:
      errors-handling:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "use built-in errors/fmt packages"
  gocyclo:
    min-complexity: 16
  cyclop:
    max-complexity: 16
  dupl:
    threshold: 128
  funlen:
    lines: 128
    statements: 64
  goconst:
    min-len: 4
    min-occurrences: 3
  misspell:
    locale: US
    ignore-words:
      - istio
      - k8s
  lll:
    line-length: 180
  goimports:
    local-prefixes: github.com/maistra/odh-platform
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - commentFormatting # https://github.com/go-critic/go-critic/issues/755
      - hugeParam # seems to be premature optimization based on https://github.com/Maistra/istio-workspace/pull/378#discussion_r392208906
  nestif:
    min-complexity: 8
  unused:
    check-exported: true
  gocognit:
    min-complexity: 20
  wrapcheck:
    ignoreSigs:
      - fmt.Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
  revive:
    rules:
      - name: dot-imports
        arguments:
          - allowedPackages: [
            "github.com/onsi/ginkgo/v2",
            "github.com/onsi/gomega",
            "github.com/onsi/gomega/gstruct",
            "github.com/opendatahub-io/odh-platform/test/matchers"
          ]
  importas:
    alias:
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: k8serr
      # Ensures that i.e. k8s.io/api/rbac/v1 is aliased as rbacv1
      - pkg: k8s.io/api/(\w+)/(v[\w\d]+)
        alias: $1$2
      - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
        alias: apiextv1
      - pkg: github.com/(openshift)/api/(\w+)/(v[\w\d]+)
        alias: $1$2$3
      - pkg: github.com/kuadrant/(authorino)/api/(v[\w\d]+)
        alias: $1$2
      - pkg: (istio).io/api/(\w+)/(v[\w\d]+)
        alias: $1$2$3
      - pkg: (istio).io/client-go/pkg/apis/(\w+)/(v[\w\d]+)
        alias: $1$2$3
  ireturn:
    allow:
      # defaults https://golangci-lint.run/usage/linters/#ireturn
      - anon
      - error
      - empty
      - stdlib
      # also allow generics
      - generic
      # we want to return spi.Interfaces in routing.go and authconfig.go
      - spi
      # for custom Gomega matchers
      - types.GomegaMatcher
  varnamelen: 
    ignore-names:
      - g # g Gomega
      - vs # VirtualService
linters:
  enable-all: true
  disable:
    - err113
    - exhaustruct
    - forbidigo
    - gofmt # We use goimports and when using them both leads to contradicting errors
    - gofumpt
    - mnd
    - paralleltest
    - prealloc

    # Temporarily ignored due to "wip"
    - godox

    # Deprecated
    - gomnd

run:
  timeout: 10m

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: test/
      linters:
        - goconst
        - gocyclo
        - golint
        - errcheck
        - dupl
        - gosec
        - revive
        - stylecheck
        - wrapcheck
    # Exclude particular linters for tests files.
    - path: _test\.go
      linters:
        - gochecknoglobals
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - revive
        - wrapcheck
    - path: _suite_test\.go
      linters:
        - revive
        - unused
