name: linters
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  pull-requests: read
  checks: write
jobs:
  go-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go env
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
          skip-cache: true
          args: --timeout 5m0s
