apiVersion: v1
kind: Service
metadata:
  name: {{ .PublicServiceName }} # the name of the service outside the mesh
  namespace: {{ .GatewayNamespace }} # the namespace of the gateway pod
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .PublicServiceName }}-certs # the serving secret for tls
spec:
  selector:
    {{ .IngressSelectorLabel }}: {{ .IngressSelectorValue }} # selects gateway pod(s)
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP

---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .PublicServiceName }}
  namespace: {{ .GatewayNamespace }}
spec:
  selector:
    {{ .IngressSelectorLabel }}: {{ .IngressSelectorValue }}
  servers:
  - hosts:
{{ range $host := .PublicHosts }}
    - {{ $host }}
{{ end }}
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{ .PublicServiceName }}-certs # see Service definition
      mode: SIMPLE

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .PublicServiceName }}
  namespace: {{ .GatewayNamespace }}
spec:
  gateways:
  - {{ .PublicServiceName }} # Gateway for public service
  - mesh # for clients in the mesh
  hosts:
{{ range $host := .PublicHosts }}
    - {{ $host }}
{{ end }}
  http:
  - name: {{ .PublicServiceName }}
    route:
    - destination:
        host: {{ .ServiceName }}.{{ .ServiceNamespace }}.svc.cluster.local   # srv k8s
        port:
          number: {{ .ServiceTargetPort }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .PublicServiceName }}
  namespace: {{ .GatewayNamespace }}
spec:
  host: {{ .PublicServiceName }}.{{ .GatewayNamespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
